import React, { createContext, useContext, ReactNode, useMemo } from 'react';

export interface ConfigContextProps {
  /** Custom prefix for autogenerated IDs */
  idPrefix?: string;
  children?: ReactNode;
}

const ConfigContext = createContext<ConfigContextProps>({});

export const ConfigProvider = (props: ConfigContextProps) => {
  const { idPrefix, children } = props;

  const value = useMemo(() => ({ idPrefix }), [idPrefix]);

  return (
    <ConfigContext.Provider value={value}>{children}</ConfigContext.Provider>
  );
};

export const useConfig = () => useContext(ConfigContext);
